// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    IAntDesignShopTwotone: typeof import('~icons/ant-design/shop-twotone')['default']
    IBiShop: typeof import('~icons/bi/shop')['default']
    IIcOutlineShoppingBag: typeof import('~icons/ic/outline-shopping-bag')['default']
    IPhUserFill: typeof import('~icons/ph/user-fill')['default']
    IRiLockPasswordFill: typeof import('~icons/ri/lock-password-fill')['default']
    LogIn: typeof import('./src/components/LogIn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShopHome: typeof import('./src/components/ShopHome.vue')['default']
  }
}

export {}
